source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'TXSwizzling_Tests', :exclusive => true do
  pod "TXSwizzling", :path => "../"

  pod 'Kiwi'
  
  link_with "TXSwizzling", "TXSwizzling_Tests"
end
